### ISSUE TITLE
Add YAML editor for tools

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#1156]
Instead of form fields in the frontend, we should configure the metadata for tools in a yaml editor. 
Part of the initial YAML editor should be: 
- Persistent session image(s)
- Provisioned session image(s)
- Backup image (Temporary solution until https://github.com/DSD-DBS/capella-collab-manager/pull/722 is merged)

The YAML would shall look like:

```yml
name: Capella

persistent-sessions:
  - id: native-capella
    image: k3d-myregistry.localhost:12345/capella/remote:$version-latest
    name: Native Capella

provisioned-sessions: # optional key
  - image: k3d-myregistry.localhost:12345/capella/readonly:$version-latest
    id: native-capella # Must be unique in list of provisioned-sessions
    name: Native Capella

# Temporary solution until https://github.com/DSD-DBS/capella-collab-manager/pull/722 is merged.
# Optional key
backup-image: k3d-myregistry.localhost:12345/t4c/client/base:$version-latest
```

The largest changes are: 
- `read-only` sessions are renamed to `provisioned` sessions. This is required for https://github.com/DSD-DBS/capella-collab-manager/issues/1004.
- Persistent sessions and provisioned sessions are now lists, meaning that a tool can define different images. This has to be considered during session spawning. The feature is required for https://github.com/DSD-DBS/capella-collab-manager/issues/859.
- Each session type can have it's custom name now -> A tool can named differently than what is displayed in the session creation component.

Depends on https://github.com/DSD-DBS/capella-collab-manager/issues/1135.
