### ISSUE TITLE
Overwrite resources for individual tool users

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#1951]
Since our production instances have an increased number of users, the user base got also diverse. We have many different resource requirements for users.

Instead of fixed resources, add different resource profiles for tools: 

```yml
config:
  resources:
    profiles:
      default:
        cpu:
          requests: 0.5
          limits: 1
        memory:
          requests: 2Gi
          limits: 4Gi
      high:
        cpu:
          requests: 1.2
          limits: 2
        memory:
          requests: 4.5Gi
          limits: 7Gi
        usernames: 
          - janedoe
          - johndoe
```

The default profile is required and doesn't apply to all users per default. Additional profiles are allowed and require a `usernames` attribute. A username can only be listed in one profile. If the user is listed in the profile, the profile will apply for the user. The tool configuration has to be updated for removed and auto-renamed users.

Open questions: 
- Do we want to use the user id instead of the username in the list? The we don't need to handle username changes, but it's less intuitive.
- Do we want to do a proper database mapping to users? Then we would need a UI instead of YAML editor.
