### ISSUE TITLE
Offer a beta program for new features

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#1952]
We often have the urge to test new features, but don't want to roll it out to all users, especially for new versions of the Capella Docker images. Therefore, we should spawn a beta program. Users should be able to opt-in and opt-out on their own. Admins should be able to opt-in and opt-out all individual users.

A new beta flag shall be added the user database table. 

The tool version configuration should change to: 

```
id: 21
name: 7.0.0
config:
  is_recommended: true
  is_deprecated: false
  sessions:
    persistent:
      image: 
        default: hello-world:v1.0.0
        beta: hello-world:v2.0.0-pre
  backups:
    image: dbb-set-docker-prod-local.bahnhub.tech.rz.db.de/t4c/client/base:7.0.0-v2.6.0-v0.2.0
  compatible_versions: []
```

The `beta` key is optional. If it's specified, spawn the corresponding image for all beta users. It it's missing or the value is None, the default image shall be used.
